# -*- coding: utf-8 -*-
"""pythonSet5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_BkjZddffzUczmevOdRSXalWd0ZT6Ot
"""

import transformers

from transformers import pipeline

result = pipeline("text-generation")

responce = result("I love Pakistan")[0]['generated_text']

print(responce)

res2 = pipeline("question-answering")

context = "Love is a complex and multifaceted emotion that has been the subject of art, literature, and philosophy for centuries. It can manifest in different forms, such as romantic love between partners, familial love between family members, and the deep affection shared among friends. Love is often characterized by feelings of deep connection, care, and compassion. It can bring immense joy, but also vulnerability, as people open their hearts to others. Some argue that love is a fundamental human need, essential for both emotional well-being and personal growth. Despite its universality, the experience of love is deeply personal and can differ widely from one individual to another. From ancient poetry to modern psychology, love continues to be a central theme in understanding what it means to be human."
question = "is love a joy?"

result2 = res2(question=question, context=context)

print(result2['answer'])

res4 = pipeline("summarization")

text = ("AI jobs are rapidly expanding as artificial intelligence reshapes industries worldwide. These roles encompass a wide range of positions, including machine learning engineers, data scientists, AI researchers, and robotics specialists. Key responsibilities often include developing algorithms, training models, analyzing large datasets, and creating intelligent systems to automate tasks or solve complex problems. Many AI roles require strong skills in programming (Python, TensorFlow, etc.), mathematics, and data analysis. The demand for AI talent is increasing in sectors like healthcare, finance, automotive, and tech. As AI continues to evolve, new job opportunities, such as AI ethics consultants and AI product managers, are also emerging.")

summary = res4(text, max_length=15, min_length=5, do_sample=False)

# Output the summary
print(summary)
print(summary[0]['summary_text'])

spam_pipeline = pipeline("text-classification", model="nlptown/bert-base-multilingual-uncased-sentiment")


text = "Congratulations! You've won a free gift card. Click here to claim."
result = spam_pipeline(text)

print(result)

topic_pipeline = pipeline("zero-shot-classification")

text = "The latest advancements in AI are transforming healthcare."
candidate_labels = ["technology", "healthcare", "sports", "politics"]
result = topic_pipeline(text, candidate_labels)

print(result)

text2 = "Technology is advancing rapidly, with artificial intelligence driving innovations in healthcare, improving diagnostics, and personalizing treatment. Meanwhile, climate change remains a pressing global issue, prompting discussions on sustainability and renewable energy solutions. In the realm of education, online learning platforms are revolutionizing access to knowledge, enabling students worldwide to thrive."
candidate_labels2 = ["Technology", "artificial intelligence", "climate change", "education","sustainability"]
result2 = topic_pipeline(text2, candidate_labels2)

print(result2['labels'])

