# -*- coding: utf-8 -*-
"""HuggingFace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124kt0EsStoh4AKc0dFLULMpegir1o5_d
"""

import transformers
from transformers import pipeline

responce = pipeline("ner")

example = "My name is Wolfgang and I live in Berlin"

ner_results = responce(example)
print(ner_results)
print(ner_results[0]['entity'])
print(ner_results[0]['index'])
print(ner_results[0]['word'])
print(ner_results[1]['entity'])
print(ner_results[1]['index'])
print(ner_results[1]['word'])

example2 = 'Ayaz, a 34-year-old who was previously a web developer, is now diving into the field of AI. Based in Karachi, Pakistan, Ayaz has a passion for machine learning and natural language processing. After spending several years working on various web development projects, he decided to transition into AI, aiming to solve complex problems with data-driven solutions. As of September 22, 2024, Ayaz is focusing on Hugging Face Transformers as his first step in AI learning. He enjoys working in Google Colab for tasks like Named Entity Recognition and is excited about analyzing data and exploring different AI algorithms. Ayaz plans to further his expertise in AI and contribute to cutting-edge research in the field.'

ner_results = responce(example2)
print(ner_results)
print(ner_results[0]['entity']," : ",ner_results[0]['word'])
print(ner_results[1]['entity']," : ",ner_results[1]['word'])
print(ner_results[2]['entity']," : ",ner_results[2]['word'])
print(ner_results[3]['entity']," : ",ner_results[3]['word'])
print(ner_results[4]['entity']," : ",ner_results[4]['word'])
print(ner_results[5]['entity']," : ",ner_results[5]['word'])
print(ner_results[6]['entity']," : ",ner_results[6]['word'])
print(ner_results[7]['entity']," : ",ner_results[7]['word'])
print(ner_results[8]['entity']," : ",ner_results[8]['word'])
print(ner_results[9]['entity']," : ",ner_results[9]['word'])
print(ner_results[10]['entity']," : ",ner_results[10]['word'])
print(ner_results[11]['entity']," : ",ner_results[11]['word'])
print(ner_results[12]['entity']," : ",ner_results[12]['word'])
print(ner_results[13]['entity']," : ",ner_results[13]['word'])
print(ner_results[14]['entity']," : ",ner_results[14]['word'])
print(ner_results[15]['entity']," : ",ner_results[15]['word'])
print(ner_results[16]['entity']," : ",ner_results[16]['word'])

